# Site settings
title: xy xy 
description: 'Ich bin ein erfahrener Manager mit langjähriger Erfahrung in der Chemielogistik und der Metallindustrie. Als Niederlassungsleiter, Business Development Manager und Vertriebsleiter habe ich Standorte und Teams mit bis zu 300 Mitarbeitenden geführt, Umsatzbudgets von bis zu 500 Mio. € verantwortet und erfolgreich neue Niederlassungen aufgebaut. Berufsbegleitend habe ich 3 Masterstudiengänge absolviert und eine Lean Six Sigma Black Belt Ausbildung abgeschlossen. In diesem Blog möchte ich mein in Praxis und Theorie erworbenes Wissen nutzen, um aktuelle Themen aus den Bereichen Change Management, Business Development, Supply Chain Management, Logistik und Prozessmanagement zu diskutieren.'
url: 'https://mexord.github.io'
baseurl: '/mrblog3'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'JMDD DJDJ'
  email: josh@joshgerdes.com
  twitter_username: joshgerdes
  facebook_username: joshgerdes
  github_username:  joshgerdes
  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
